# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env: 
    FILE_PATH: home/runner/work/LambdaHelloWorld/LambdaHelloWorld/target/LambdaHelloWorld-1.0-SNAPSHOT-shaded.jar
    DEPLOYMENT_PACKAGE_NAME: lambda_deployment.zip

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn package
      
    - name: Archive Release
      run: zip -r ${{ env.DEPLOYMENT_PACKAGE_NAME }}  \terget\LambdaHelloWorld-1.0-SNAPSHOT-shaded.jar
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ${{ secrets.AWS_REGION }}
       
    - name: Deploy Lambda function
      uses: yvesgurcan/deploy-lambda-function@v0.0.5
      with:
       package: ${{ env.DEPLOYMENT_PACKAGE_NAME }}
       function-name: ${{ secrets.AWS_FUNCTION_NAME }}
       AWS_REGION: ${{ secrets.AWS_REGION }}
       AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
